# Reads javaResults.csv generated by ConditionedMRCAPriorSampler,
# runs the same R simulation, and plots both distributions overlaid per node.
library(nnls)
library(nleqslv)
library(truncdist)
library(ggplot2)
library(ggpubr)
library(latex2exp)

# ── parameters ──────────────────────
parent <- c(NA, 1, 1, 3, 2, 2, 6, 6, 8, 9)
t_lo   <- c(10.0, 9.4, 4.8, 4.0, 8.0, 6.8, 1.8, 2.0, 1.7, 1.6)
t_hi   <- c(10.5, 9.6, 5.0, 5.0, 9.5, 8.0, 2.5, 3.2, 2.5, 2.5)
N <- length(parent)
p_cov  <- 0.90
n_sim  <- 50000

# ── load Java samples ─────────────────────────────────────────────────────────
java_wsim  <- read.csv("./javaResults.csv")
stopifnot(nrow(java_wsim) == n_sim, ncol(java_wsim) == N)

# ── R simulation (same logic as calibrationprior_simulation.r) ────────────────
compute_log_targets <- function(t_l, t_u, p) {
  z     <- qnorm((1 + p) / 2)
  sigma <- (log(t_u) - log(t_l)) / (2 * z)
  list(mu = log(t_l) + z * sigma, sigma2 = sigma^2)
}

invert_logmoments_to_beta <- function(m, v) {
  Ey <- exp(m + v / 2)
  Vy <- exp(2 * m + v) * (exp(v) - 1)
  if (Vy >= Ey * (1 - Ey)) Vy <- 0.99 * Ey * (1 - Ey)
  ab_sum <- Ey * (1 - Ey) / Vy - 1
  a0 <- max(1e-3, Ey * ab_sum)
  b0 <- max(1e-3, (1 - Ey) * ab_sum)
  F  <- function(par) {
    a <- par[1]; b <- par[2]
    c(digamma(a) - digamma(a + b) - m,
 trigamma(a) - trigamma(a + b) - v)
  }
  sol <- nleqslv(c(a0, b0), F)
  list(alpha = sol$x[1], beta = sol$x[2])
}

safe_rlnorm_trunc <- function(meanlog, sdlog, upper_vec) {
  out <- numeric(length(upper_vec))
  for (k in seq_along(upper_vec)) {
    u <- upper_vec[k]
    if (is.na(u) || u <= 0) { out[k] <- NA_real_; next }
    if (plnorm(u, meanlog, sdlog) < 1e-8) {
 out[k] <- runif(1, 0.5, 0.9) * u
    } else {
 out[k] <- rtrunc(1, "lnorm", a = 0, b = u, meanlog = meanlog, sdlog = sdlog)
    }
  }
  out
}

is_beta_node    <- rep(TRUE, N)
is_beta_node[1] <- FALSE
for (i in 2:N) {
  if (!is.na(parent[i]) && t_hi[i] <= t_lo[parent[i]]) is_beta_node[i] <- FALSE
}

log_targets <- lapply(1:N, function(i) compute_log_targets(t_lo[i], t_hi[i], p_cov))
mu_vec <- sapply(log_targets, `[[`, "mu")
sigma2_vec <- sapply(log_targets, `[[`, "sigma2")

edges <- which(is_beta_node & !is.na(parent))
n_edges    <- length(edges)
edge_names <- paste(parent[edges], edges, sep = "_")
A_mean     <- diag(n_edges)
b_mean     <- sapply(seq_along(edges), function(k) mu_vec[edges[k]] - mu_vec[parent[edges[k]]])
b_var <- sapply(seq_along(edges), function(k) sigma2_vec[edges[k]])

m_hat <- solve(A_mean, b_mean)
v_hat <- pmax(nnls(A_mean, b_var)$x, 1e-6)

beta_params <- lapply(1:n_edges, function(j) invert_logmoments_to_beta(m_hat[j], v_hat[j]))
edge_alpha  <- setNames(sapply(beta_params, `[[`, "alpha"), edge_names)
edge_beta   <- setNames(sapply(beta_params, `[[`, "beta"),  edge_names)

r_wsim <- matrix(NA_real_, nrow = n_sim, ncol = N)
r_wsim[, 1] <- rlnorm(n_sim, mu_vec[1], sqrt(sigma2_vec[1]))
for (i in 2:N) {
  par_i <- parent[i]
  if (is.na(par_i)) next
  if (is_beta_node[i]) {
    key    <- paste(par_i, i, sep = "_")
    r_wsim[, i] <- r_wsim[, par_i] * rbeta(n_sim, edge_alpha[key], edge_beta[key])
  } else {
    r_wsim[, i] <- safe_rlnorm_trunc(mu_vec[i], sqrt(sigma2_vec[i]), r_wsim[, par_i])
  }
}

# ── per-node coverage + statistical tests ────────────────────────────────────
r_cov    <- sapply(1:N, function(i) mean(r_wsim[, i]    >= t_lo[i] & r_wsim[, i]    <= t_hi[i]))
java_cov <- sapply(1:N, function(i) mean(java_wsim[, i] >= t_lo[i] & java_wsim[, i] <= t_hi[i]))
ks_p     <- sapply(1:N, function(i) ks.test(r_wsim[, i], java_wsim[, i])$p.value)
t_p      <- sapply(1:N, function(i) t.test(r_wsim[, i],  java_wsim[, i])$p.value)
mean_diff <- sapply(1:N, function(i) mean(java_wsim[, i]) - mean(r_wsim[, i]))

alpha <- 0.05
cat("\n── Per-node R vs Java (n =", n_sim, ", alpha =", alpha, ")────────────────────────\n")
cat(sprintf("%-6s %-9s %-9s %-10s %-6s %-11s %-9s %-6s\n",
            "Node", "R-cov", "Java-cov", "KS p-val", "KS", "mean-diff", "t p-val", "t-test"))
for (i in 1:N)
  cat(sprintf("%-6d %-9.4f %-9.4f %-10.4f %-6s %-11.5f %-9.4f %-6s\n",
              i, r_cov[i], java_cov[i],
              ks_p[i],   ifelse(ks_p[i] > alpha, "PASS", "FAIL"),
              mean_diff[i],
              t_p[i],    ifelse(t_p[i]  > alpha, "PASS", "FAIL")))
cat(sprintf("KS: %d/%d pass | t-test: %d/%d pass\n\n", sum(ks_p > alpha), N, sum(t_p > alpha), N))

# ── overlaid density plots ────────────────────────────────────────────────────
plots <- vector("list", N)
for (i in 1:N) {
  df <- rbind(
    data.frame(value = r_wsim[, i],    source = "R"),
    data.frame(value = java_wsim[, i], source = "Java")
  )
  plots[[i]] <- ggplot(df, aes(x = value, fill = source, colour = source)) +
    geom_density(alpha = 0.35, linewidth = 0.7) +
    geom_vline(xintercept = t_lo[i], colour = "black", linetype = "dashed", linewidth = 0.5) +
    geom_vline(xintercept = t_hi[i], colour = "black", linetype = "dashed", linewidth = 0.5) +
    scale_fill_manual(values   = c(R = "#E69F00", Java = "#56B4E9")) +
    scale_colour_manual(values = c(R = "#E69F00", Java = "#56B4E9")) +
    labs(
 title = paste0("Node ", i,
  "  R=", round(r_cov[i], 3),
  "  Java=", round(java_cov[i], 3),
  "  KS p=", round(ks_p[i], 3)),
 x = TeX(paste0("$T_{", i, "}$")), y = "Density"
    ) +
    theme_minimal() +
    theme(plot.title = element_text(size = 9, face = "bold"),
     legend.position = if (i == 1) "right" else "none")
}

panel <- ggarrange(plotlist = plots, ncol = 2, nrow = ceiling(N / 2))
print(panel)
